In [2]:
import pandas as pd

# dataframe = pd.read_csv("./data/ecommerce_data.csv", index_col=0)
dataframe = pd.read_csv("./data/ecommerce_data.csv")
dataframe.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [14]:
# dataframe["InvoiceDate"] = pd.to_datetime(dataframe["InvoiceDate"], dayfirst=True)
dataframe["InvoiceDate"] = pd.to_datetime(dataframe["InvoiceDate"])
# dataframe["InvoiceNo"] = dataframe["InvoiceNo"].astype(int)
dataframe.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [4]:
len(dataframe)

541909

In [6]:
import sqlite3

# DB setup for retrieval
connection = sqlite3.connect("database.db")
dataframe.to_sql("ecommerce_table", connection, if_exists="replace")

541909

In [7]:
from google.genai import Client, types
from dotenv import load_dotenv
import os
load_dotenv()

gemini = Client(api_key=os.getenv("GEMINI_API_KEY"))

# SYSTEM_PROMPT = """"""
# gemini_config = types.GenerateContentConfig(
#     system_instruction=SYSTEM_PROMPT,
#     thinking_config=types.ThinkingConfig(
#         thinking_budget=0
#     )
# )

result = gemini.models.generate_content(
    model="gemini-2.5-flash-lite",
    contents="Write a haiku about the glory to achieved from intelligence, passionate work, wisdom and character"
)

print(result.text)

Mind's bright spark ignites,
Passion fuels the work's hard climb,
Wisdom's glow, character's strength.

In [8]:
def sql_tool(query: str):
    """Run a SQL SELECT query on a SQLite database and return the results."""
    return pd.read_sql_query(query, connection).to_dict(orient="records")

In [11]:
sql_tool(
    "SELECT * FROM ecommerce_table;"
)

[{'index': 0,
  'InvoiceNo': '536365',
  'StockCode': '85123A',
  'Description': 'WHITE HANGING HEART T-LIGHT HOLDER',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 08:26:00',
  'UnitPrice': 2.55,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 1,
  'InvoiceNo': '536365',
  'StockCode': '71053',
  'Description': 'WHITE METAL LANTERN',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 08:26:00',
  'UnitPrice': 3.39,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 2,
  'InvoiceNo': '536365',
  'StockCode': '84406B',
  'Description': 'CREAM CUPID HEARTS COAT HANGER',
  'Quantity': 8,
  'InvoiceDate': '2010-12-01 08:26:00',
  'UnitPrice': 2.75,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 3,
  'InvoiceNo': '536365',
  'StockCode': '84029G',
  'Description': 'KNITTED UNION FLAG HOT WATER BOTTLE',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 08:26:00',
  'UnitPrice': 3.39,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 4,
  'InvoiceNo': '536365',
  'StockCode': '84029E',
  'Description': 'RED WOOLLY HOTTIE WHITE HEART.',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 08:26:00',
  'UnitPrice': 3.39,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 5,
  'InvoiceNo': '536365',
  'StockCode': '22752',
  'Description': 'SET 7 BABUSHKA NESTING BOXES',
  'Quantity': 2,
  'InvoiceDate': '2010-12-01 08:26:00',
  'UnitPrice': 7.65,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 6,
  'InvoiceNo': '536365',
  'StockCode': '21730',
  'Description': 'GLASS STAR FROSTED T-LIGHT HOLDER',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 08:26:00',
  'UnitPrice': 4.25,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 7,
  'InvoiceNo': '536366',
  'StockCode': '22633',
  'Description': 'HAND WARMER UNION JACK',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 08:28:00',
  'UnitPrice': 1.85,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 8,
  'InvoiceNo': '536366',
  'StockCode': '22632',
  'Description': 'HAND WARMER RED POLKA DOT',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 08:28:00',
  'UnitPrice': 1.85,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 9,
  'InvoiceNo': '536367',
  'StockCode': '84879',
  'Description': 'ASSORTED COLOUR BIRD ORNAMENT',
  'Quantity': 32,
  'InvoiceDate': '2010-12-01 08:34:00',
  'UnitPrice': 1.69,
  'CustomerID': 13047.0,
  'Country': 'United Kingdom'},
 {'index': 10,
  'InvoiceNo': '536367',
  'StockCode': '22745',
  'Description': "POPPY'S PLAYHOUSE BEDROOM ",
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 08:34:00',
  'UnitPrice': 2.1,
  'CustomerID': 13047.0,
  'Country': 'United Kingdom'},
 {'index': 11,
  'InvoiceNo': '536367',
  'StockCode': '22748',
  'Description': "POPPY'S PLAYHOUSE KITCHEN",
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 08:34:00',
  'UnitPrice': 2.1,
  'CustomerID': 13047.0,
  'Country': 'United Kingdom'},
 {'index': 12,
  'InvoiceNo': '536367',
  'StockCode': '22749',
  'Description': 'FELTCRAFT PRINCESS CHARLOTTE DOLL',
  'Quantity': 8,
  'InvoiceDate': '2010-12-01 08:34:00',
  'UnitPrice': 3.75,
  'CustomerID': 13047.0,
  'Country': 'United Kingdom'},
 {'index': 13,
  'InvoiceNo': '536367',
  'StockCode': '22310',
  'Description': 'IVORY KNITTED MUG COSY ',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 08:34:00',
  'UnitPrice': 1.65,
  'CustomerID': 13047.0,
  'Country': 'United Kingdom'},
 {'index': 14,
  'InvoiceNo': '536367',
  'StockCode': '84969',
  'Description': 'BOX OF 6 ASSORTED COLOUR TEASPOONS',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 08:34:00',
  'UnitPrice': 4.25,
  'CustomerID': 13047.0,
  'Country': 'United Kingdom'},
 {'index': 15,
  'InvoiceNo': '536367',
  'StockCode': '22623',
  'Description': 'BOX OF VINTAGE JIGSAW BLOCKS ',
  'Quantity': 3,
  'InvoiceDate': '2010-12-01 08:34:00',
  'UnitPrice': 4.95,
  'CustomerID': 13047.0,
  'Country': 'United Kingdom'},
 {'index': 16,
  'InvoiceNo': '536367',
  'StockCode': '22622',
  'Description': 'BOX OF VINTAGE ALPHABET BLOCKS',
  'Quantity': 2,
  'InvoiceDate': '2010-12-01 08:34:00',
  'UnitPrice': 9.95,
  'CustomerID': 13047.0,
  'Country': 'United Kingdom'},
 {'index': 17,
  'InvoiceNo': '536367',
  'StockCode': '21754',
  'Description': 'HOME BUILDING BLOCK WORD',
  'Quantity': 3,
  'InvoiceDate': '2010-12-01 08:34:00',
  'UnitPrice': 5.95,
  'CustomerID': 13047.0,
  'Country': 'United Kingdom'},
 {'index': 18,
  'InvoiceNo': '536367',
  'StockCode': '21755',
  'Description': 'LOVE BUILDING BLOCK WORD',
  'Quantity': 3,
  'InvoiceDate': '2010-12-01 08:34:00',
  'UnitPrice': 5.95,
  'CustomerID': 13047.0,
  'Country': 'United Kingdom'},
 {'index': 19,
  'InvoiceNo': '536367',
  'StockCode': '21777',
  'Description': 'RECIPE BOX WITH METAL HEART',
  'Quantity': 4,
  'InvoiceDate': '2010-12-01 08:34:00',
  'UnitPrice': 7.95,
  'CustomerID': 13047.0,
  'Country': 'United Kingdom'},
 {'index': 20,
  'InvoiceNo': '536367',
  'StockCode': '48187',
  'Description': 'DOORMAT NEW ENGLAND',
  'Quantity': 4,
  'InvoiceDate': '2010-12-01 08:34:00',
  'UnitPrice': 7.95,
  'CustomerID': 13047.0,
  'Country': 'United Kingdom'},
 {'index': 21,
  'InvoiceNo': '536368',
  'StockCode': '22960',
  'Description': 'JAM MAKING SET WITH JARS',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 08:34:00',
  'UnitPrice': 4.25,
  'CustomerID': 13047.0,
  'Country': 'United Kingdom'},
 {'index': 22,
  'InvoiceNo': '536368',
  'StockCode': '22913',
  'Description': 'RED COAT RACK PARIS FASHION',
  'Quantity': 3,
  'InvoiceDate': '2010-12-01 08:34:00',
  'UnitPrice': 4.95,
  'CustomerID': 13047.0,
  'Country': 'United Kingdom'},
 {'index': 23,
  'InvoiceNo': '536368',
  'StockCode': '22912',
  'Description': 'YELLOW COAT RACK PARIS FASHION',
  'Quantity': 3,
  'InvoiceDate': '2010-12-01 08:34:00',
  'UnitPrice': 4.95,
  'CustomerID': 13047.0,
  'Country': 'United Kingdom'},
 {'index': 24,
  'InvoiceNo': '536368',
  'StockCode': '22914',
  'Description': 'BLUE COAT RACK PARIS FASHION',
  'Quantity': 3,
  'InvoiceDate': '2010-12-01 08:34:00',
  'UnitPrice': 4.95,
  'CustomerID': 13047.0,
  'Country': 'United Kingdom'},
 {'index': 25,
  'InvoiceNo': '536369',
  'StockCode': '21756',
  'Description': 'BATH BUILDING BLOCK WORD',
  'Quantity': 3,
  'InvoiceDate': '2010-12-01 08:35:00',
  'UnitPrice': 5.95,
  'CustomerID': 13047.0,
  'Country': 'United Kingdom'},
 {'index': 26,
  'InvoiceNo': '536370',
  'StockCode': '22728',
  'Description': 'ALARM CLOCK BAKELIKE PINK',
  'Quantity': 24,
  'InvoiceDate': '2010-12-01 08:45:00',
  'UnitPrice': 3.75,
  'CustomerID': 12583.0,
  'Country': 'France'},
 {'index': 27,
  'InvoiceNo': '536370',
  'StockCode': '22727',
  'Description': 'ALARM CLOCK BAKELIKE RED ',
  'Quantity': 24,
  'InvoiceDate': '2010-12-01 08:45:00',
  'UnitPrice': 3.75,
  'CustomerID': 12583.0,
  'Country': 'France'},
 {'index': 28,
  'InvoiceNo': '536370',
  'StockCode': '22726',
  'Description': 'ALARM CLOCK BAKELIKE GREEN',
  'Quantity': 12,
  'InvoiceDate': '2010-12-01 08:45:00',
  'UnitPrice': 3.75,
  'CustomerID': 12583.0,
  'Country': 'France'},
 {'index': 29,
  'InvoiceNo': '536370',
  'StockCode': '21724',
  'Description': 'PANDA AND BUNNIES STICKER SHEET',
  'Quantity': 12,
  'InvoiceDate': '2010-12-01 08:45:00',
  'UnitPrice': 0.85,
  'CustomerID': 12583.0,
  'Country': 'France'},
 {'index': 30,
  'InvoiceNo': '536370',
  'StockCode': '21883',
  'Description': 'STARS GIFT TAPE ',
  'Quantity': 24,
  'InvoiceDate': '2010-12-01 08:45:00',
  'UnitPrice': 0.65,
  'CustomerID': 12583.0,
  'Country': 'France'},
 {'index': 31,
  'InvoiceNo': '536370',
  'StockCode': '10002',
  'Description': 'INFLATABLE POLITICAL GLOBE ',
  'Quantity': 48,
  'InvoiceDate': '2010-12-01 08:45:00',
  'UnitPrice': 0.85,
  'CustomerID': 12583.0,
  'Country': 'France'},
 {'index': 32,
  'InvoiceNo': '536370',
  'StockCode': '21791',
  'Description': 'VINTAGE HEADS AND TAILS CARD GAME ',
  'Quantity': 24,
  'InvoiceDate': '2010-12-01 08:45:00',
  'UnitPrice': 1.25,
  'CustomerID': 12583.0,
  'Country': 'France'},
 {'index': 33,
  'InvoiceNo': '536370',
  'StockCode': '21035',
  'Description': 'SET/2 RED RETROSPOT TEA TOWELS ',
  'Quantity': 18,
  'InvoiceDate': '2010-12-01 08:45:00',
  'UnitPrice': 2.95,
  'CustomerID': 12583.0,
  'Country': 'France'},
 {'index': 34,
  'InvoiceNo': '536370',
  'StockCode': '22326',
  'Description': 'ROUND SNACK BOXES SET OF4 WOODLAND ',
  'Quantity': 24,
  'InvoiceDate': '2010-12-01 08:45:00',
  'UnitPrice': 2.95,
  'CustomerID': 12583.0,
  'Country': 'France'},
 {'index': 35,
  'InvoiceNo': '536370',
  'StockCode': '22629',
  'Description': 'SPACEBOY LUNCH BOX ',
  'Quantity': 24,
  'InvoiceDate': '2010-12-01 08:45:00',
  'UnitPrice': 1.95,
  'CustomerID': 12583.0,
  'Country': 'France'},
 {'index': 36,
  'InvoiceNo': '536370',
  'StockCode': '22659',
  'Description': 'LUNCH BOX I LOVE LONDON',
  'Quantity': 24,
  'InvoiceDate': '2010-12-01 08:45:00',
  'UnitPrice': 1.95,
  'CustomerID': 12583.0,
  'Country': 'France'},
 {'index': 37,
  'InvoiceNo': '536370',
  'StockCode': '22631',
  'Description': 'CIRCUS PARADE LUNCH BOX ',
  'Quantity': 24,
  'InvoiceDate': '2010-12-01 08:45:00',
  'UnitPrice': 1.95,
  'CustomerID': 12583.0,
  'Country': 'France'},
 {'index': 38,
  'InvoiceNo': '536370',
  'StockCode': '22661',
  'Description': 'CHARLOTTE BAG DOLLY GIRL DESIGN',
  'Quantity': 20,
  'InvoiceDate': '2010-12-01 08:45:00',
  'UnitPrice': 0.85,
  'CustomerID': 12583.0,
  'Country': 'France'},
 {'index': 39,
  'InvoiceNo': '536370',
  'StockCode': '21731',
  'Description': 'RED TOADSTOOL LED NIGHT LIGHT',
  'Quantity': 24,
  'InvoiceDate': '2010-12-01 08:45:00',
  'UnitPrice': 1.65,
  'CustomerID': 12583.0,
  'Country': 'France'},
 {'index': 40,
  'InvoiceNo': '536370',
  'StockCode': '22900',
  'Description': ' SET 2 TEA TOWELS I LOVE LONDON ',
  'Quantity': 24,
  'InvoiceDate': '2010-12-01 08:45:00',
  'UnitPrice': 2.95,
  'CustomerID': 12583.0,
  'Country': 'France'},
 {'index': 41,
  'InvoiceNo': '536370',
  'StockCode': '21913',
  'Description': 'VINTAGE SEASIDE JIGSAW PUZZLES',
  'Quantity': 12,
  'InvoiceDate': '2010-12-01 08:45:00',
  'UnitPrice': 3.75,
  'CustomerID': 12583.0,
  'Country': 'France'},
 {'index': 42,
  'InvoiceNo': '536370',
  'StockCode': '22540',
  'Description': 'MINI JIGSAW CIRCUS PARADE ',
  'Quantity': 24,
  'InvoiceDate': '2010-12-01 08:45:00',
  'UnitPrice': 0.42,
  'CustomerID': 12583.0,
  'Country': 'France'},
 {'index': 43,
  'InvoiceNo': '536370',
  'StockCode': '22544',
  'Description': 'MINI JIGSAW SPACEBOY',
  'Quantity': 24,
  'InvoiceDate': '2010-12-01 08:45:00',
  'UnitPrice': 0.42,
  'CustomerID': 12583.0,
  'Country': 'France'},
 {'index': 44,
  'InvoiceNo': '536370',
  'StockCode': '22492',
  'Description': 'MINI PAINT SET VINTAGE ',
  'Quantity': 36,
  'InvoiceDate': '2010-12-01 08:45:00',
  'UnitPrice': 0.65,
  'CustomerID': 12583.0,
  'Country': 'France'},
 {'index': 45,
  'InvoiceNo': '536370',
  'StockCode': 'POST',
  'Description': 'POSTAGE',
  'Quantity': 3,
  'InvoiceDate': '2010-12-01 08:45:00',
  'UnitPrice': 18.0,
  'CustomerID': 12583.0,
  'Country': 'France'},
 {'index': 46,
  'InvoiceNo': '536371',
  'StockCode': '22086',
  'Description': "PAPER CHAIN KIT 50'S CHRISTMAS ",
  'Quantity': 80,
  'InvoiceDate': '2010-12-01 09:00:00',
  'UnitPrice': 2.55,
  'CustomerID': 13748.0,
  'Country': 'United Kingdom'},
 {'index': 47,
  'InvoiceNo': '536372',
  'StockCode': '22632',
  'Description': 'HAND WARMER RED POLKA DOT',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 09:01:00',
  'UnitPrice': 1.85,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 48,
  'InvoiceNo': '536372',
  'StockCode': '22633',
  'Description': 'HAND WARMER UNION JACK',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 09:01:00',
  'UnitPrice': 1.85,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 49,
  'InvoiceNo': '536373',
  'StockCode': '85123A',
  'Description': 'WHITE HANGING HEART T-LIGHT HOLDER',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 09:02:00',
  'UnitPrice': 2.55,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 50,
  'InvoiceNo': '536373',
  'StockCode': '71053',
  'Description': 'WHITE METAL LANTERN',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 09:02:00',
  'UnitPrice': 3.39,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 51,
  'InvoiceNo': '536373',
  'StockCode': '84406B',
  'Description': 'CREAM CUPID HEARTS COAT HANGER',
  'Quantity': 8,
  'InvoiceDate': '2010-12-01 09:02:00',
  'UnitPrice': 2.75,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 52,
  'InvoiceNo': '536373',
  'StockCode': '20679',
  'Description': 'EDWARDIAN PARASOL RED',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 09:02:00',
  'UnitPrice': 4.95,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 53,
  'InvoiceNo': '536373',
  'StockCode': '37370',
  'Description': 'RETRO COFFEE MUGS ASSORTED',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 09:02:00',
  'UnitPrice': 1.06,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 54,
  'InvoiceNo': '536373',
  'StockCode': '21871',
  'Description': 'SAVE THE PLANET MUG',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 09:02:00',
  'UnitPrice': 1.06,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 55,
  'InvoiceNo': '536373',
  'StockCode': '21071',
  'Description': 'VINTAGE BILLBOARD DRINK ME MUG',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 09:02:00',
  'UnitPrice': 1.06,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 56,
  'InvoiceNo': '536373',
  'StockCode': '21068',
  'Description': 'VINTAGE BILLBOARD LOVE/HATE MUG',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 09:02:00',
  'UnitPrice': 1.06,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 57,
  'InvoiceNo': '536373',
  'StockCode': '82483',
  'Description': 'WOOD 2 DRAWER CABINET WHITE FINISH',
  'Quantity': 2,
  'InvoiceDate': '2010-12-01 09:02:00',
  'UnitPrice': 4.95,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 58,
  'InvoiceNo': '536373',
  'StockCode': '82486',
  'Description': 'WOOD S/3 CABINET ANT WHITE FINISH',
  'Quantity': 4,
  'InvoiceDate': '2010-12-01 09:02:00',
  'UnitPrice': 6.95,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 59,
  'InvoiceNo': '536373',
  'StockCode': '82482',
  'Description': 'WOODEN PICTURE FRAME WHITE FINISH',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 09:02:00',
  'UnitPrice': 2.1,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 60,
  'InvoiceNo': '536373',
  'StockCode': '82494L',
  'Description': 'WOODEN FRAME ANTIQUE WHITE ',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 09:02:00',
  'UnitPrice': 2.55,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 61,
  'InvoiceNo': '536373',
  'StockCode': '84029G',
  'Description': 'KNITTED UNION FLAG HOT WATER BOTTLE',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 09:02:00',
  'UnitPrice': 3.39,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 62,
  'InvoiceNo': '536373',
  'StockCode': '84029E',
  'Description': 'RED WOOLLY HOTTIE WHITE HEART.',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 09:02:00',
  'UnitPrice': 3.39,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 63,
  'InvoiceNo': '536373',
  'StockCode': '22752',
  'Description': 'SET 7 BABUSHKA NESTING BOXES',
  'Quantity': 2,
  'InvoiceDate': '2010-12-01 09:02:00',
  'UnitPrice': 7.65,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 64,
  'InvoiceNo': '536373',
  'StockCode': '21730',
  'Description': 'GLASS STAR FROSTED T-LIGHT HOLDER',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 09:02:00',
  'UnitPrice': 4.25,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 65,
  'InvoiceNo': '536374',
  'StockCode': '21258',
  'Description': 'VICTORIAN SEWING BOX LARGE',
  'Quantity': 32,
  'InvoiceDate': '2010-12-01 09:09:00',
  'UnitPrice': 10.95,
  'CustomerID': 15100.0,
  'Country': 'United Kingdom'},
 {'index': 66,
  'InvoiceNo': '536375',
  'StockCode': '85123A',
  'Description': 'WHITE HANGING HEART T-LIGHT HOLDER',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 09:32:00',
  'UnitPrice': 2.55,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 67,
  'InvoiceNo': '536375',
  'StockCode': '71053',
  'Description': 'WHITE METAL LANTERN',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 09:32:00',
  'UnitPrice': 3.39,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 68,
  'InvoiceNo': '536375',
  'StockCode': '84406B',
  'Description': 'CREAM CUPID HEARTS COAT HANGER',
  'Quantity': 8,
  'InvoiceDate': '2010-12-01 09:32:00',
  'UnitPrice': 2.75,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 69,
  'InvoiceNo': '536375',
  'StockCode': '20679',
  'Description': 'EDWARDIAN PARASOL RED',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 09:32:00',
  'UnitPrice': 4.95,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 70,
  'InvoiceNo': '536375',
  'StockCode': '37370',
  'Description': 'RETRO COFFEE MUGS ASSORTED',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 09:32:00',
  'UnitPrice': 1.06,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 71,
  'InvoiceNo': '536375',
  'StockCode': '21871',
  'Description': 'SAVE THE PLANET MUG',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 09:32:00',
  'UnitPrice': 1.06,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 72,
  'InvoiceNo': '536375',
  'StockCode': '21071',
  'Description': 'VINTAGE BILLBOARD DRINK ME MUG',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 09:32:00',
  'UnitPrice': 1.06,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 73,
  'InvoiceNo': '536375',
  'StockCode': '21068',
  'Description': 'VINTAGE BILLBOARD LOVE/HATE MUG',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 09:32:00',
  'UnitPrice': 1.06,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 74,
  'InvoiceNo': '536375',
  'StockCode': '82483',
  'Description': 'WOOD 2 DRAWER CABINET WHITE FINISH',
  'Quantity': 2,
  'InvoiceDate': '2010-12-01 09:32:00',
  'UnitPrice': 4.95,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 75,
  'InvoiceNo': '536375',
  'StockCode': '82486',
  'Description': 'WOOD S/3 CABINET ANT WHITE FINISH',
  'Quantity': 4,
  'InvoiceDate': '2010-12-01 09:32:00',
  'UnitPrice': 6.95,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 76,
  'InvoiceNo': '536375',
  'StockCode': '82482',
  'Description': 'WOODEN PICTURE FRAME WHITE FINISH',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 09:32:00',
  'UnitPrice': 2.1,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 77,
  'InvoiceNo': '536375',
  'StockCode': '82494L',
  'Description': 'WOODEN FRAME ANTIQUE WHITE ',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 09:32:00',
  'UnitPrice': 2.55,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 78,
  'InvoiceNo': '536375',
  'StockCode': '84029G',
  'Description': 'KNITTED UNION FLAG HOT WATER BOTTLE',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 09:32:00',
  'UnitPrice': 3.39,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 79,
  'InvoiceNo': '536375',
  'StockCode': '84029E',
  'Description': 'RED WOOLLY HOTTIE WHITE HEART.',
  'Quantity': 6,
  'InvoiceDate': '2010-12-01 09:32:00',
  'UnitPrice': 3.39,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 80,
  'InvoiceNo': '536375',
  'StockCode': '22752',
  'Description': 'SET 7 BABUSHKA NESTING BOXES',
  'Quantity': 2,
  'InvoiceDate': '2010-12-01 09:32:00',
  'UnitPrice': 7.65,
  'CustomerID': 17850.0,
  'Country': 'United Kingdom'},
 {'index': 81,
  'InvoiceNo': '536375',
  'StockCode': '21730',

In [ ]:
SYSTEM_PROMPT = """
You are an expert SQL analyst. When appropriate, generate SQL queries based on the user's question and the database schema.
When you generate a query, user 'sql_tool' function to execute the query on the database and get the results.
Then use the results to answer the user's question.

database_schema: [
    {
        table: 'ecommerce_table',
        columns: [
            {
                name: 
            }
        ]
    }
]
""".strip()